# Generated by Django 4.1.2 on 2023-01-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
    ]
