# Generated by Django 4.2.11 on 2024-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_project_image_skill_image_skill_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
