# Generated by Django 4.2.11 on 2024-03-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_skill_image_alter_skill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_name',
            field=models.ImageField(blank=True, null=True, upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project'),
        ),
    ]
